FROM ubuntu:latest     # this is mmy base image form where the deploymanet will be done

LABEL author="aditya"

RUN apt-get update && \
    apt-get install apache2 unzip -y

ADD https://templatemo.com/download/templatemo_606_string_master /var/www/html/

RUN rm -rf /var/www/html/index.html && \
    unzip /var/www/html/templatemo_606_string_master.zip -d /var/www/html/ && \
    mv /var/www/html/templatemo_606_string_master/* /var/www/html/
#in here we have removed the default index.html file of apaceh server and unzipped the download webapp
# and moved all the content to apache server root directory

EXPOSE 80
#we are exposing port  80 ot access our webapp

CMD [ "apache2ctl", "-D", "FOREGROUND" ] 
#we get this from the documentation only here we write the process whis is to run just sear for the image
