apiVersion: v1
metadata:
  name: rc
  labels:
    app: rcapp
kind: replicaController
spec:
  replicas: 3
  template:
    metadata:
      name: lb-pod
      labels:
        app: podlb
    spec:
      containers:
      - name: nginx-container
        image: nginx
        ports:
        - containerPort: 80
  selector:
    matchLabels:
      app: podlb
