apiVersion: v1
metadata:
  name: my-pod
  labels:
    app: myapp
kind: Pod
spec:
  volumes:
  - name: nginxvol
    persistentVolumeClaim:
      claimName: pv-claim
  containers:
  - name: nginxcont
    image: nginx
    volumemounts:
    - name: nginxvol
      mountPath: "/share/local/nginx/"
    ports:
    - containerPort: 80
      protocol: TCP
