apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-volume
  labels:
    app: pv-volume
spec:
  accessModes:
  - ReadWriteOnce # data can be read/written by single node
  capacity:
    # amouint of storage pc can alot from ectenal volumes/ebs
    storage: 15Gi
  storageClassName: standard # matches with pvc and depends on the type of ecternal volume]
  volumeMode: Filesystem # since ebs is used we use this volume mode
  persistentVolumeReclaimPolicy: Retain # data will retained even after pv is deleted
  hostPath:
    path: /mnt/data/nginxvol1

# ensure accessmodes , storageClassnaem and volume modes matches with pvc
